### ISSUE TITLE
The "Effect" Widget don't hide particle

### ISSUE THREAD

**Issue by Ephilem** [Stevertus/objD#12]
Hey,

This Effect widget for example :
`Effect(EffectType.invisibility, duration: 100000, showParticles: false)`
don't work because the export is : 
`ActiveEffects:[{Id:14,Amplifier:0,Duration:2000000,ShowParticles:0}]`

And for hide particle, the `ShowParticles:0` need a b like that `ShowParticles:0b`.

I thinks it's I'm on the version 1.16.1 on Minecraft and ObjD havn't updated on this version.

Thanks

(PS: Sorry for my english)

**Comment by Stevertus** [comment]
This will be fixed in 0.3.5. Meanwhile you can use Git as source for your pubspec if this breaks something
```yaml
dependencies:
  kittens:
    git: https://github.com/Stevertus/objD.git
```
Thanks for reporting this issue this clearly!
