### ISSUE TITLE
It won't install :(

### ISSUE THREAD

**Issue by MASTRIO** [Stevertus/objD#17]
I have the pubspec.yaml file setup correctly:

> name: test-datapack
> dependencies:
>     objd: <0.3.6

and the lib folder, but when I run `dart pub get` it says

> pubspec.yaml has no lower-bound SDK constraint.
> You should edit pubspec.yaml to contain an SDK constraint:
> 
> environment:
>   sdk: '>=2.10.0 <3.0.0'
> 
> See https://dart.dev/go/sdk-constraint

I've looked up multiple solutions but none of them worked

**Comment by AdrianCapacite** [comment]
If you copy the environment and SDK below that and paste it anywhere in your pubspec.yaml it should work, make sure you restart VS Code after doing so.
```
name: test-datapack
dependencies:
  objd: <0.3.6
environment:
  sdk: '>=2.10.0 <3.0.0
```

**Comment by MASTRIO** [comment]
ah ok, I'll have to try that later 👍

**Comment by Stevertus** [comment]
Yeah this version did not support the latest version of the dart sdk yet. But actually today I updated objD. Make sure you include this to have all the latest features:
```yaml
environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  objd: ^0.4.0
```
